version: "3.9"

services:
  xampp:
    image: tomsik68/xampp:latest
    container_name: uniconnect_xampp
    privileged: true
    ports:
      - "8080:80"
    volumes:
      - /workspaces/UniConnect:/opt/lampp/htdocs/UniConnect:Z
    environment:
      MYSQL_ROOT_PASSWORD: uc_root_password
      MYSQL_USER: uniconnect
      MYSQL_PASSWORD: uc_password
      MYSQL_DATABASE: uniconnect_db
    restart: unless-stopped
